### ISSUE TITLE
List on OperatorHub.io?

### ISSUE THREAD

**Issue by liamdawson** [mittwald/kubernetes-secret-generator#14]
I've found OperatorHub.io to be quite useful for having a "package manager" for operators, without going down the whole Helm path. I had a shot at generating a definition for what this would look like on the site, but didn't want to publish it if I wasn't the owner!

### secret-generator.package.yaml
```yaml
packageName: secret-generator
channels:
  - name: stable
    currentCSV: secret-generator.v2.1.1
```

### secret-generator.v2.1.1.clusterserviceversion.yaml
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: secret-generator.v2.1.1
  namespace: placeholder
  annotations:
    alm-examples: '[]'
    categories: 'Security, Developer Tools'
    certified: 'false'
    createdAt: ''
    description: >-
      A controller that can automatically create random secret values. This may
      be used for auto-generating random credentials for applications run on
      Kubernetes.
    containerImage: ''
    support: ''
    capabilities: Basic Install
    repository: ''
spec:
  displayName: Secret Generator
  description: >+
    This operator generates random secret values, such as passwords. It also
    provides functionality to regenerate these values easily.

    ## Operator Usage


    Add the annotation `secret-generator.v1.mittwald.de/autogenerate` to any
    Kubernetes secret object. The value of the annotation can be a field name
    (or comma separated list of field names) within the secret; the
    SecretGeneratorController will pick up this annotation and add a field \[or
    fields] (password in the example below) to the secret with a randomly
    generated string value.


    ```

    apiVersion: v1

    kind: Secret

    metadata:
      annotations:
        secret-generator.v1.mittwald.de/autogenerate: password
    data:
      username: c29tZXVzZXI=
    ```


    Operational tasks:

    * Regenerate all automatically generator passwords:

      `$ kubectl annotate secrets --all secret-generator.v1.mittwald.de/regenerate=true`
    * Regenerate only certain fields:

      `$ kubectl annotate secrets --all secret-generator.v1.mittwald.de/regenerate=password1,password2`

  maturity: stable
  version: 2.1.1
  replaces: ''
  minKubeVersion: ''
  keywords:
    - secrets
  maintainers:
    - name: ''
      email: ''
  provider:
    name: Mittwald CM Service
  labels: {}
  selector:
    matchLabels: {}
  links:
    - name: Repo
      url: 'https://github.com/mittwald/kubernetes-secret-generator'
  icon:
    - base64data: ''
      mediatype: ''
  customresourcedefinitions:
    owned: []
    required: []
  install:
    strategy: deployment
    spec:
      permissions: []
      clusterPermissions:
        - serviceAccountName: secret-generator
          rules:
            - apiGroups: '""'
              resources:
                - secrets
              verbs:
                - get
                - watch
                - list
                - update
      deployments:
        - name: secret-generator-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: secret-generator
            template:
              metadata:
                labels:
                  app: secret-generator
              spec:
                serviceAccountName: secret-generator
                containers:
                  - name: secret-generator
                    image: 'quay.io/mittwald/kubernetes-secret-generator:latest'
                    command:
                      - /kubernetes-secret-generator
                    args:
                      - '-logtostderr'
                      - '-all-namespaces'
                      - '-regenerate-insecure'
  installModes:
    - type: OwnNamespace
      supported: false
    - type: SingleNamespace
      supported: false
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: true
```
