### ISSUE TITLE
Support generating self-signed TLS Secrets

### ISSUE THREAD

**Issue by Skeen** [mittwald/kubernetes-secret-generator#45]
**Is your feature request related to a problem? Please describe.**
It would be convenient to be able to generate `kubernetes.io/tls` secrets, for self-signed TLS on ingress controllers.

**Describe the solution you'd like**
I'd like to be able to specify my TLS secret alike:
```
apiVersion: v1
kind: Secret
metadata:
  name: tls-cert
  annotations:
    secret-generator.v1.mittwald.de/type: tls
    secret-generator.v1.mittwald.de/duration: 365
    secret-generator.v1.mittwald.de/common_name: example.org
    secret-generator.v1.mittwald.de/organisation: example.org
    ...
data: {}
```
With the resulting secret being equivalent to running:
```
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${KEY_FILE} -out ${CERT_FILE} -subj "/CN=example.org/O=example.org"
$ kubectl create secret tls tls-cert --key ${KEY_FILE} --cert ${CERT_FILE}
```

**Describe alternatives you've considered**
Using Let's Encrypt whenever available, however sometimes the ingress is not internet-facing, or the DNS is local, and thus Let's Encrypt via the Ingress is not an option either.

Running the above two lines to generate secrets by hand.
