### ISSUE TITLE
Allow passing custom annotations to CR-generated secrets

### ISSUE THREAD

**Issue by aiceball** [mittwald/kubernetes-secret-generator#73]
**Is your feature request related to a problem? Please describe.**
When using secrets generated by CR definitions I am unable to add custom annotations at deployment time.
Custom annotations on generated secrets are useful when using something like `reflector`. 

On old-format (annotation-based) secrets that was not a problem, however CR-based secrets are much cleaner for GitOps diffing.

**Describe the solution you'd like**
Allow passing annotations from CR definitions to generated secrets, something like:

```
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: "example-pw"
  namespace: "default"
spec:
  annotations:
    <insert your custom annotations for the created secret here>
  forceRegenerate: false
  data:
    username: "testuser"
  fields:
    - fieldName: "test"
      encoding: "hex"
      length: "15"
```

**Describe alternatives you've considered**
Falling back onto annotation-based secret generation, but inconvenient when using GitOps, as the diffs are detected as out of sync.
